Revert "Fix logcat spam for samsung devices"
This is giving build error due to missing headers.

hardware/u8500/media/libstelpcutils/OMXdebug.cpp:5747:20: error: 'OMX_STE_IndexConfigCommonZoomMode' was not declared in this scope
hardware/u8500/media/libstelpcutils/OMXdebug.cpp:5748:20: error: 'OMX_STE_IndexConfigMeteringOn' was not declared in this scope
hardware/u8500/media/libstelpcutils/OMXdebug.cpp:10853:20: error: 'OMX_STE_IndexConfigExifTimestamp' was not declared in this scope

Change-Id: I13c716aac6bf419d95ec6b2fc229b14f2bbe8571